language: node_js
node_js: "node"
cache:
  directories:
    - node_modules

script:
  - npm run export

deploy:
  - provider: script
    script: npx now --public -t $NOW_T ./out && npx now -t $NOW_T alias
    skip_cleanup: true
