name: build-deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: lint
      run: |
        ops/bin/lint
    - name: build
      run: |
        ops/bin/build
    - name: deploy
      if: github.ref == 'refs/heads/master'
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        NOW_PROJECT_ID: ${{ secrets.NOW_PROJECT_ID }}
        NOW_ORG_ID: ${{ secrets.NOW_ORG_ID }}
      run: |
        ops/bin/deploy
